# Generated by Django 4.1.13 on 2026-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='coordinator_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='landline_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
