# Generated by Django 4.1.13 on 2026-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='tution_fees',
        ),
        migrations.AddField(
            model_name='school',
            name='tution_fees_from_school',
            field=models.BooleanField(default=False),
        ),
    ]
