# Generated by Django 4.1.13 on 2026-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_school_tution_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='tution_fees_from_school',
        ),
        migrations.AddField(
            model_name='school',
            name='fees_taken_from',
            field=models.CharField(choices=[('parents', 'Parents'), ('school', 'School')], default='parents', max_length=20),
        ),
    ]
