# Generated by Django 4.1.13 on 2026-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_school_tution_fees_from_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rte',
            field=models.BooleanField(default=False),
        ),
    ]
