# Generated by Django 4.1.13 on 2026-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_student_rte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='fees',
            new_name='tution_fees',
        ),
    ]
