# Generated by Django 4.1.13 on 2026-05-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_rename_fees_course_tution_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tution_fees',
            new_name='tuition_fees',
        ),
    ]
