# Generated by Django 4.1.13 on 2026-06-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_coursetype_courselevel_alter_course_course_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
