# Generated by Django 4.1.13 on 2026-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreceipt',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
