# Generated by Django 4.1.13 on 2026-06-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_studentreceipt_parent_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreceipt',
            name='parent_contact',
        ),
    ]
