# Generated by Django 4.1.13 on 2026-06-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_remove_student_level'),
        ('billing', '0004_billingdocument_billingdocumentitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingDocument',
            new_name='InvoiceDocument',
        ),
        migrations.RenameModel(
            old_name='BillingDocumentItem',
            new_name='InvoiceDocumentItem',
        ),
    ]
