# Generated by Django 4.1.13 on 2026-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_billingdocument_invoicedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedocument',
            name='document_no',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
