# Generated by Django 4.1.13 on 2026-06-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_invoicedocument_document_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedocument',
            name='city',
            field=models.CharField(blank=True, default='PUNE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='gst_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='pan_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='state',
            field=models.CharField(blank=True, default='MAHARASHTRA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='state_code',
            field=models.CharField(blank=True, default='27', max_length=10, null=True),
        ),
    ]
