# Generated by Django 4.1.13 on 2026-06-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycareStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('child_photo', models.ImageField(blank=True, null=True, upload_to='daycare/child/')),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_photo', models.ImageField(blank=True, null=True, upload_to='daycare/parent/')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('hours_per_day', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days_per_month', models.IntegerField(default=30)),
                ('monthly_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selected_services', models.JSONField(blank=True, default=list)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='daycare.company')),
            ],
        ),
    ]
