# Generated by Django 4.1.13 on 2026-05-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0009_rename_tution_fees_course_tuition_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('book', 'Book'), ('instrument', 'Instrument'), ('bag', 'Bag')], max_length=20)),
                ('course_type', models.CharField(blank=True, choices=[('vedic_maths', 'Vedic Maths'), ('abacus', 'Abacus')], max_length=50, null=True)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.course')),
            ],
        ),
    ]
