# Generated by Django 4.1.13 on 2026-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_type',
            field=models.CharField(choices=[('vedic_maths', 'Vedic Maths'), ('abacus', 'Abacus'), ('common', 'Common')], default='common', max_length=50),
            preserve_default=False,
        ),
    ]
