# Generated by Django 4.1.13 on 2026-05-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_vendor_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=100, unique=True)),
                ('grn_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='inventory.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.IntegerField()),
                ('received_qty', models.IntegerField()),
                ('accepted_qty', models.IntegerField()),
                ('damaged_qty', models.IntegerField(default=0)),
                ('unit', models.CharField(default='PCS', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.grn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
