# Generated by Django 4.1.13 on 2026-05-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sold_stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='inward_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='outward_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('DAMAGED', 'Damaged'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='inventory.product')),
            ],
        ),
    ]
