# Generated by Django 4.1.13 on 2026-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_stock_sold_stock_stock_inward_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='billable_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='replacement_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
