# Generated by Django 4.1.13 on 2026-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorderitem_billable_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitem',
            name='replacement_received_qty',
            field=models.IntegerField(default=0),
        ),
    ]
