# Generated by Django 4.1.13 on 2026-05-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_grnitem_replacement_received_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grnitem',
            old_name='replacement_received_qty',
            new_name='replacement_qty',
        ),
    ]
