# Generated by Django 4.1.13 on 2026-06-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_replacement_received_qty_grnitem_replacement_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDamagedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_damaged_qty', models.IntegerField(default=0)),
                ('settled_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damaged_items', to='inventory.vendor')),
            ],
        ),
    ]
