# Generated by Django 4.1.13 on 2026-06-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_vendordamagedstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendordamagedstock',
            unique_together={('vendor', 'product')},
        ),
    ]
