# Generated by Django 4.1.13 on 2026-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_vendordamagedstock_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='operating_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
