# Generated by Django 4.1.13 on 2026-06-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_coursetype_courselevel_alter_course_course_type_and_more'),
        ('inventory', '0013_vendor_category_vendor_operating_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.coursetype'),
        ),
    ]
