# Generated by Django 4.1.13 on 2026-06-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_remove_student_level'),
        ('inventory', '0014_alter_product_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.courselevel'),
        ),
    ]
